### PR TITLE
MIT, Columbia, Boston University

### PR DESCRIPTION
**Pull request by HussainAther**
I've added Columbia University and Boston University to the list of graduate programs in computational neuroscience. I've also filled out the professors I've found for the MIT graduate program in computational neuroscience.

### CODE REVIEW

**Comment by HussainAther** [comment]
Fixed links for Columbia section

**Comment by HussainAther** [comment]
Added Johns Hopkins University as well as some faculty that may be relevant.

**Comment by HussainAther** [comment]
move Scandinavian countries under Europe

**Comment by HussainAther** [comment]
Change "Stanford" to "Stanford University" and change "University of Indiana" to "Indiana University"

**Comment by HussainAther** [comment]
Add "Stephanie Palmer" and her info to U Chicago.

**Comment by HussainAther** [comment]
Add University of Minnesota and the corresponding PI's.

**Comment by eselkin** [comment]
Sorry it took me so long, I was on a trip. Excellent additions and changes!

**Comment by HussainAther** [comment]
No problem. Thanks!

**Pull request merged**
